bots/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import django
from django.contrib import admin
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import views as auth_views

from . import botsglobal
from . import views

if django.get_version() > '2':
    from django.urls import include, re_path
else:
    from django.conf.urls import include, url as re_path


staff_required = user_passes_test(lambda u: u.is_staff)
superuser_required = user_passes_test(lambda u: u.is_superuser)
run_permission = user_passes_test(lambda u: u.has_perm('bots.change_mutex'))


bots_paths = [
    # login required
    re_path(r'^home.*', login_required(views.home), name='home'),
    re_path(r'^incoming.*', login_required(views.incoming), name='incoming'),
    re_path(r'^outgoing.*', login_required(views.outgoing), name='outgoing'),
    re_path(r'^detail.*', login_required(views.detail), name='detail'),
    re_path(r'^process.*', login_required(views.process), name='process'),
    re_path(r'^document.*', login_required(views.document), name='document'),
    re_path(r'^reports.*', login_required(views.reports), name='reports'),
    re_path(r'^confirm.*', login_required(views.confirm), name='confirm'),
    re_path(r'^filer.*', login_required(views.filer), name='filer'),
    re_path(r'^srcfiler.*', login_required(views.srcfiler), name='srcfiler'),
    re_path(r'^logfiler.*', login_required(views.logfiler), name='logfiler'),
    # only staff
    re_path(r'^runengine.+', run_permission(views.runengine), name='runengine'),
    # only superuser
    re_path(r'^delete.*', superuser_required(views.delete), name='delete'),
    re_path(r'^plugin/index.*', superuser_required(views.plugin_index), name='plugin_index'),
    re_path(r'^plugin.*', superuser_required(views.plugin), name='plugin'),
    re_path(r'^plugout/index.*', superuser_required(views.plugout_index), name='plugout_index'),
    re_path(r'^plugout/backup.*', superuser_required(views.plugout_backup), name='plugout_backup'),
    re_path(r'^plugout.*', superuser_required(views.plugout), name='plugout'),
    re_path(r'^sendtestmail.*', superuser_required(views.sendtestmailmanagers), name='sendtestmail'),
    # catch-all
    re_path(r'^.*', views.index),
]

if django.get_version() > '2':
    auth_paths = [
        # Auth
        re_path(
            r'^login.*', auth_views.LoginView.as_view(template_name='admin/login.html'),
            name='login',
        ),
        re_path(
            r'^logout.*', auth_views.LogoutView.as_view(next_page='/'),
            name='logout',
        ),
    ]
    if botsglobal.ini.getboolean('webserver', 'menu_changepassword', True):
        auth_paths += [
            re_path(
                r'^password_change/$', auth_views.PasswordChangeView.as_view(),
                name='password_change',
            ),
            re_path(
                r'^password_change/done/$', auth_views.PasswordChangeDoneView.as_view(),
                name='password_change_done',
            ),
        ]

else:
    auth_paths = [
        # Auth
        re_path(
            r'^login.*', auth_views.login,
            {'template_name': 'admin/login.html'},
            name='login',
        ),
        re_path(
            r'^logout.*', auth_views.logout,
            {'next_page': '/'},
            name='logout',
        ),
    ]
    if botsglobal.ini.getboolean('webserver', 'menu_changepassword', True):
        auth_paths += [
            re_path(
                r'^password_change/$', auth_views.password_change,
                name='password_change',
            ),
            re_path(
                r'^password_change/done/$', auth_views.password_change_done,
                name='password_change_done',
            ),
    ]


urlpatterns = auth_paths + [
    # only staff
    # do not show django admin root page
    # re_path(r'^admin/$', login_required(views.home)),
    # do not show django admin root page
    # re_path(r'^admin/bots/$', login_required(views.home)),
    re_path(r'^admin/', admin.site.urls),
    # Bots urls
    re_path('bots/', include((bots_paths, 'bots'), namespace='bots')),
    re_path(r'^.*', views.index),
]

handler500 = 'bots.views.server_error'

bots/templates/bots/confirm.html
{% extends "bots/base.html" %}
{% load i18n botsfilters %}

{% block bodyclass %}{{ block.super }} confirm{% endblock %}

{% block bots_title %}
<h1 class="ico-{% if form.confirmidta.value == 0 %}pending{% else %}confirmed{{ form.confirmed.value }}{% endif %}"><a href="#" title="{% trans 'Top' %}">{{ title }}</a> {% include "bots/selection/view.html" %}</h1>
{% endblock %}

{% block bots_submit %}
<button class="button ico-incoming" name="2incoming">{% trans 'Incoming (same selection)' %}</button>
<button class="button ico-outgoing" name="2outgoing">{% trans 'Outgoing (same selection)' %}</button>
{% if form.confirmidta.value < 1 %}<button class="button ico-no" onclick="document.getElementById('id_confirmidta').value='';">{% trans 'All confirmations' %}</button>{% endif %}
{% if form.confirmidta.value != -1 %}<button class="button ico-confirmed" onclick="document.getElementById('id_confirmidta').value=-1;">{% trans 'Manual confirm' %}</button>{% endif %}
{% if form.confirmidta.value != 0 %}<button class="button ico-pending" onclick="document.getElementById('id_confirmidta').value=0;">{% trans 'Pending (same selection)' %}</button>{% endif %}
{{ block.super }}
{% if not perms.bots.change_mutex %}{% include 'bots/botstable/field/hidden.html' with field=form.idroute %}
{% include 'bots/botstable/field/hidden.html' with field=form.fromchannel %}
{% include 'bots/botstable/field/hidden.html' with field=form.tochannel %}{% endif %}
{% endblock %}

{% block botstable %}
<thead>
<tr>
    {% include 'bots/botstable/thead/selall.html' %}
    {% include 'bots/botstable/thead/field.html' with field=form.idta %}
    {% include 'bots/botstable/thead/field.html' with field=form.confirmed %}
    <th id="th_ts"><button class="botsheader ico-ts" name="order" value="ts">{% trans 'Date/time' %}</button></th>
    <th id="th_filename"><button class="botsheader ico-file" name="order" value="filename" >{% trans 'File' %}</button></th>
    <th id="th_reference"><button class="botsheader" name="order" value="reference" >{% trans 'Reference' %}</button></th>
    {% include 'bots/botstable/thead/field.html' with field=form.confirmtype %}
    {% include 'bots/botstable/thead/field.html' with field=form.confirmidta %}
    {% include 'bots/botstable/thead/field.html' with field=form.editype %}
    {% include 'bots/botstable/thead/field.html' with field=form.messagetype %}
    {% if perms.bots.change_mutex %}{% include 'bots/botstable/thead/field.html' with field=form.idroute %}
    {% include 'bots/botstable/thead/field.html' with field=form.fromchannel %}
    {% include 'bots/botstable/thead/field.html' with field=form.tochannel %}{% endif %}
    {% include 'bots/botstable/thead/field.html' with field=form.frompartner %}
    {% include 'bots/botstable/thead/field.html' with field=form.topartner %}
</tr>
<tr>
    {% if not form.actions.is_hidden %}<th></th>{% endif %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.idta %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.confirmed get_field_display=True icon="ico-confirmed" cssclass=form.confirmed.value %}
    {% include 'bots/botstable/thead/datefields.html' %}
    {% include 'bots/botstable/thead/textfield.html' with field=form.filename %}
    {% include 'bots/botstable/thead/textfield.html' with field=form.reference %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.confirmtype get_field_display=True %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.confirmidta %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.editype %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.messagetype %}
    {% if perms.bots.change_mutex %}{% include 'bots/botstable/thead/filtered.html' with field=form.idroute %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.fromchannel %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.tochannel %}{% endif %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.frompartner %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.topartner %}
</tr>
</thead>
<tbody>{% for row in queryset.object_list %}
<tr class="{% cycle 'row1' 'row2' %}">
    {% include 'bots/botstable/td/sel.html' %}
    <td><div class="dropdown">
      {% if perms.bots.view_ta %}<a href="{% url 'bots:detail' %}/?outidta={{ row.idta }}" name="bots_detail_{{ row.idta }}" onclick="return popup(this, '95%', '75%', '&popup=1')" title="{% trans 'View details' %}: {{ row.idta }}" class="button ico-{% if row.confirmidta == 0 %}pending{% else %}confirmed{{ row.confirmed }}{% endif %}">{{ row.idta }}</a>
      {% else %}<button type="button" class="button ico-confirmed{{ row.confirmed }}">{{ row.idta }}</button>{% endif %}
      {% if not row.confirmidta and perms.bots.change_ta %}<ul>
        <li><button value="{{ row.idta }}" class="ico-confirmed" onclick="if (!confirm(this.innerText + ': ' + this.value)){return false;}; this.name = 'confirm';">{% trans 'Confirm manual' %}</button></li>
      </ul>{% endif %}
    </div></td>
    {% include 'bots/botstable/td/confirmed.html' %}
    {% include 'bots/botstable/td/ts.html' %}
    {% include 'bots/botstable/td/filename.html' %}
    {% include 'bots/botstable/td/reference.html' %}
    {% include 'bots/botstable/td/confirmtype.html' %}
    <td>{% include 'bots/link/confirmation.html' with ta=row %}</td>
    {% include 'bots/botstable/td/editype.html' %}
    {% include 'bots/botstable/td/messagetype.html' %}
    {% if perms.bots.change_mutex %}{% include 'bots/botstable/td/idroute.html' %}
    {% include 'bots/botstable/td/fromchannel.html' %}
    {% include 'bots/botstable/td/tochannel.html' %}{% endif %}
    {% include 'bots/botstable/td/frompartner.html' %}
    {% include 'bots/botstable/td/topartner.html' %}
</tr>
{% endfor %}</tbody>
{% endblock %}

bots/templates/bots/document.html
{% extends "bots/base.html" %}
{% load i18n botsfilters %}

{% block bodyclass %}{{ block.super }} document{% endblock %}

{% block bots_title %}
<h1 class="ico-docs{% if form.status.value %}{{ form.status.value }}{% endif %}"><a href="#" title="{% trans 'Top' %}">{{ title }}</a> {% include "bots/selection/view.html" %}</h1>
{% endblock %}

{% block bots_submit %}
{% if form.allstatus %}{% include 'bots/botstable/field/checkbox.html' with field=form.allstatus %}{% endif %}
{{ block.super }}{% if not perms.bots.change_mutex %}
{% include 'bots/botstable/field/hidden.html' with field=form.idroute %}
{% include 'bots/botstable/field/hidden.html' with field=form.fromchannel %}{% endif %}
{% endblock %}

{% block botstable %}
<thead>
<tr>
    {% include 'bots/botstable/thead/field.html' with field=form.status %}
    <th id="th_ts"><button class="botsheader ico-ts" name="order" value="ts">{% trans 'Date/time' %}</button></th>
    <th id="th_reference"><button class="botsheader" name="order" value="reference">{% trans 'Reference' %}</button></th>
    <th id="th_filename"><button class="botsheader ico-file" name="order" value="filename">{% trans 'File' %}</button></th>
    {% include 'bots/botstable/thead/field.html' with field=form.contenttype show_field=False %}
    {% include 'bots/botstable/thead/field.html' with field=form.editype %}
    {% include 'bots/botstable/thead/field.html' with field=form.messagetype %}
    {% if perms.bots.change_mutex %}{% include 'bots/botstable/thead/field.html' with field=form.idroute %}
    {% include 'bots/botstable/thead/field.html' with field=form.fromchannel %}{% endif %}
    {% include 'bots/botstable/thead/field.html' with field=form.confirmtype %}
    {% include 'bots/botstable/thead/field.html' with field=form.confirmidta %}
    {% include 'bots/botstable/thead/field.html' with field=form.frompartner %}
    {% include 'bots/botstable/thead/field.html' with field=form.topartner %}
    <th id="th_filesize"><button class="botsheader" name="order" value="filesize">{% trans 'Size' %}</button></th>
</tr>
<tr>
    {% include 'bots/botstable/thead/filtered.html' with field=form.status get_field_display=True icon="ico-doc" cssclass=form.status.value %}
    {% include 'bots/botstable/thead/datefields.html' %}
    {% include 'bots/botstable/thead/textfield.html' with field=form.reference %}
    {% include 'bots/botstable/thead/textfield.html' with field=form.filename %}
    {% include 'bots/botstable/thead/textfield.html' with field=form.contenttype %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.editype %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.messagetype %}
    {% if perms.bots.change_mutex %}{% include 'bots/botstable/thead/filtered.html' with field=form.idroute %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.fromchannel %}{% endif %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.confirmtype get_field_display=True %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.confirmidta %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.frompartner %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.topartner %}
    <th></th>
</tr>
</thead>
<tbody class="documents">{% for row in queryset.object_list %}
<tr class="{% cycle 'row1' 'row2' %}">
    <td data-field="status" data-value="{{ row.status }}"><div class="dropdown">
      {% if perms.bots.view_ta %}<a href="{% url 'bots:detail' %}/?{% if row.status == 200 %}in{% else %}out{% endif %}idta={{ row.idta }}" onclick="return popup(this, '95%', '75%', '&popup=1')" title="{% trans 'View details' %}: {{ row.idta }}" class="button ico-doc{{ row.status }}">{{ row.get_status_display }}</a>
      {% else %}<button class="button ico-doc{{ row.status }}">{{ row.get_status_display }}</button>{% endif %}
      <ul>
        {% if user.is_staff %}<li><a class="ico-log" href="{% url 'bots:logfiler' %}/?engine=&{% if row.status == 200 %}in{% else %}out{% endif %}idta={{ row.idta }}" target="_blank">{% trans 'View log' %}</a></li>{% endif %}
        {% if row.status == 320 and perms.bots.change_mutex %}{# document-in #}<li><button type="submit" name="rereceive" value="{{ row.idta }}" class="ico-rereceive">{% trans 'Rereceive' %}</button></li>
        {% elif row.status == 330 %}{# document-out #}{% endif %}
      {# include "bots/botstable/dropdown/filters.html" with field=form.status get_status=True #}
      </ul>
    </div></td>
    {% include 'bots/botstable/td/ts.html' %}
    {% include 'bots/botstable/td/reference.html' %}
    {% include 'bots/botstable/td/filename.html' %}
    {% include 'bots/botstable/td/contenttype.html' %}
    {% include 'bots/botstable/td/editype.html' %}
    {% include 'bots/botstable/td/messagetype.html' %}
    {% if perms.bots.change_mutex %}{% include 'bots/botstable/td/idroute.html' %}
    {% include 'bots/botstable/td/fromchannel.html' %}{% endif %}
    {% include 'bots/botstable/td/confirmtype.html' %}
    <td>{% include 'bots/link/confirmation.html' with ta=row %}</td>
    {% include 'bots/botstable/td/frompartner.html' %}
    {% include 'bots/botstable/td/topartner.html' %}
    <td>{% if row.filesize %}{{ row.filesize|filesizeformat }}{% endif %}</td>
</tr>
{% endfor %}</tbody>
{% endblock %}

bots/templates/bots/fontsizer.html
<input type="button" class="bt-round bt-less" onclick="ScaleFont(this)" value="-">{{ form.fontsize }}<input type="button" class="bt-round bt-plus" onclick="ScaleFont(this)" value="+">

bots/templates/bots/menu.html
{% load i18n static %}
<link rel="stylesheet" href="{% static "css/bots-nav.css" %}">
<nav id="bots-nav">
<ul>{% if not user.is_authenticated %}
  <li><a href="{% url 'login' %}">{% trans 'Log in' %}</a></li>
{% else %}
{% block user-nav %}
<li><a{% if not bots_touchscreen %} href="{% url 'bots:home' %}"{% endif %} class="ico-home after-title" title="{% trans 'Home' %}"></a>
  <ul>
    {% if bots_touchscreen %}<li><a href="{% url 'bots:home' %}" class="ico-home">{% trans 'Home' %}</a></li>{% endif %}
    <li><a href="https://bots.readthedocs.io/en/latest/guide-for-botsmonitor/">{% trans 'Help' %}</a></li>
    {% if user.has_usable_password and menu_changepassword %}<li><a href="{% url 'password_change' %}" class="ico-key">{% trans 'Change password' %}</a></li>{% endif %}
    <li><a href="{% url 'logout' %}" class="ico-logout">{% trans 'Log out' %}</a></li>
  </ul>
</li>
{% endblock %}
{% block bots-nav %}
{% include 'bots/nav/index.html' %}
{% endblock %}
{% endif %}
</ul>
</nav>

bots/templates/bots/plugin.html
{% extends "admin/base.html" %}
{% load i18n %}

{% block content %}
<br/>
<h1 class="ico-plugin">{% trans 'Read a plugin' %}</h1>
<br/>
<p>{% trans 'Select a plugin from your file system' %}:</p>
<form action="{% url 'bots:plugin' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
{{ form }}
<br/>
<br/>
<br/>
{% include 'bots/button_cancel_close.html' %}
<button name="submit" class="button ico-read" onclick="return (document.getElementById('id_file').value && confirm('{% trans 'Read' %}: ' + document.getElementById('id_file').files[0].name + ' ?'));">{% trans 'Read' %}</button>
</form>
{% endblock %}

bots/templates/bots/process.html
{% extends "bots/base.html" %}
{% load i18n %}

{% block bodyclass %}{{ block.super }} process{% endblock %}

{% block bots_submit %}
<button class="button ico-incoming" name="2incoming">{% trans 'Incoming (same selection)' %}</button>
<button class="button ico-outgoing" name="2outgoing">{% trans 'Outgoing (same selection)' %}</button>
{{ block.super }}
{% if not perms.bots.change_mutex %}{% include 'bots/botstable/field/hidden.html' with field=form.idroute %}
{% include 'bots/botstable/field/hidden.html' with field=form.fromchannel %}
{% include 'bots/botstable/field/hidden.html' with field=form.tochannel %}{% endif %}
{% endblock %}

{% block botstable %}
<thead>
<tr>
    <th id="th_filename"><button class="botsheader" name="order" value="filename">{% trans 'Process' %}</button></th>
    <th id="th_status"><button class="botsheader" name="order" value="status">{% trans 'State' %}</button></th>
    <th id="th_ts"><button class="botsheader ico-ts" name="order" value="ts">{% trans 'Date/time' %}</button></th>
    {% if perms.bots.change_mutex %}{% include 'bots/botstable/thead/field.html' with field=form.idroute %}
    {% include 'bots/botstable/thead/field.html' with field=form.fromchannel %}
    {% include 'bots/botstable/thead/field.html' with field=form.tochannel %}{% endif %}
    <th id="th_errortext"><button class="botsheader icon-err" name="order" value="errortext">{% trans 'Error' %}</button></th>
</tr>
<tr>
    <th></th>
    <th></th>
    {% include 'bots/botstable/thead/datefields.html' %}
    {% if perms.bots.change_mutex %}{% include 'bots/botstable/thead/filtered.html' with field=form.idroute %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.fromchannel %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.tochannel %}{% endif %}
    {% include 'bots/botstable/thead/textfield.html' with field=form.errortext %}
</tr>
</thead>
<tbody class="process">{% for row in queryset.object_list %}
<tr class="{% cycle 'row1' 'row2' %} botstrstatus{{ row.statust }}">
    <td><div class="dropdown">
      {% if perms.bots.view_ta %}<a href="{% url 'bots:detail' %}/?inidta={{ row.idta }}" name="bots_detail_{{ row.idta }}" onclick="return popup(this, '95%', '75%', '&popup=1')" title="{% trans 'View details' %}: {{ row.idta }}" class="button icon-err">{{ row.filename }}</a>
      {% else %}<button class="button">{{ row.filename }}</button>{% endif %}
    </div></td>
    <td class="botsstatus{{ row.statust }}">{{ row.get_statust_display }}</td>
    {% include 'bots/botstable/td/ts.html' %}
    {% if perms.bots.change_mutex %}{% include 'bots/botstable/td/idroute.html' %}
    {% include 'bots/botstable/td/fromchannel.html' %}
    {% include 'bots/botstable/td/tochannel.html' %}{% endif %}
    <td>{% include 'bots/ta_errortext.html' %}</td>
</tr>
{% endfor %}</tbody>
{% endblock %}

bots/templates/bots/refresh.html
{% if form.refresh and not form.refresh.is_hidden %}{% load i18n %}{{ form.refresh }}<button class="{{ cssclass|default:'pad6' }} button ico-reload" title="{% trans 'Refresh' %}"></button>{% endif %}
&nbsp;<span class="now">{% now "DATE_FORMAT" %}&nbsp;&nbsp;{% now "TIME_FORMAT" %}</span>

bots/templates/bots/reports.html
{% extends "bots/base.html" %}
{% load i18n %}

{% block bodyclass %}{{ block.super }} reports{% endblock %}

{% block botstable %}
<thead>
<tr>
    <th id="th_selall">{% if not form.actions.is_hidden %}<input type="checkbox" name="selall" onchange="checkall(this, 'sel')">{% endif %}</th>
    {% include 'bots/botstable/thead/field.html' with field=form.status %}
    <th id="th_ts"><button class="botsheader ico-ts" name="order" value="ts">{% trans 'Date/time' %}</button></th>
    {% include 'bots/botstable/thead/field.html' with field=form.type %}
    <th id="th_lastreceived"><button class="botsheader" name="order" value="lastreceived">{% trans '#in' %}</button></th>
    <th id="th_send"><button class="botsheader" name="order" value="send">{% trans '#out' %}</button></th>
    <th id="th_filesize"><button class="botsheader" name="order" value="filesize">{% trans 'Size' %}</button></th>
    <th id="th_processerrors"><button class="botsheader ico-err" name="order" value="processerrors">{% trans 'Error' %}</button></th>
    <th id="th_rsrv1"><button class="botsheader ico-run" name="order" value="rsrv1">{% trans 'Commandline' %}</button></th>
    {% include 'bots/botstable/thead/field.html' with field=form.acceptance %}
</tr>
<tr>
    <th></th>
    {% include 'bots/botstable/thead/filtered.html' with field=form.status get_field_display=True %}
    {% include 'bots/botstable/thead/datefields.html' %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.type get_field_display=True %}
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    {% include 'bots/botstable/thead/textfield.html' with field=form.rsrv1 %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.acceptance get_field_display=True %}
</tr>
</thead>
<tbody class="reports">{% for row in queryset.object_list %}
<tr class="{% cycle 'row1' 'row2' %}{% if row.status %} botstrstatus1{% endif %}">
    <td><div class="dropdown">{% if not form.actions.is_hidden %}<input type="checkbox" id="{{ row.idta }}" name="sel" value="{{ row.idta }}" onclick="checktr(this)"><label for="{{ row.idta }}" class="icon-star" title="Select {{ row.idta }}"></label>{% else %}<span class="icon-star"></span>{% endif %}
      <ul>
        {% if user.is_staff %}<li><a class="ico-log" href="{% url 'bots:logfiler' %}/?engine={{ row.idta }}" target="_blank">{% trans 'View log' %}</a></li>{% endif %}{% if row.lastreceived %}
        <li><a href="{% url 'bots:incoming' %}/?reportidta={{ row.idta }}&popup=1" target="_blank" class="ico-incoming">{% trans 'View incoming' %}</a></li>
        <li><a href="{% url 'bots:outgoing' %}/?reportidta={{ row.idta }}&popup=1" target="_blank" class="ico-outgoing">{% trans 'View out-communication' %}</a></li>{% endif %}
        {% if perms.bots.delete_report %}<li><button name="delete" value="{{ row.idta }}" class="ico-trash" onclick="return confirm(this.innerText + ': ' + this.value)">{% trans 'Delete' %} {% trans 'report' %}</button></li>{% endif %}
      </ul>
    </div></td>
    <td data-field="status" data-value="{% if not row.status %}0"><div class="dropdown icon-yes{% else %}1"><div class="dropdown {% if row.lasterror or row.lastok or row.lastopen %}icon-no{% else %}icon-alert{% endif %}{% endif %}"><ul></ul></div></td>
    {% include 'bots/botstable/td/ts.html' %}
    {% include 'bots/botstable/td/td.html' with field=form.type value=row.type %}
    <td>{% if row.lastreceived %}<a href="{% url 'bots:incoming' %}/?reportidta={{ row.idta }}" class="button" title="{% trans 'View incoming' %}">{{ row.lastreceived }}</a>{% else %}{{ row.lastreceived }}{% endif %}</td>
    <td>{% if row.send %}<a href="{% url 'bots:outgoing' %}/?reportidta={{ row.idta }}" class="button" title="{% trans 'View outgoing' %}">{{ row.send }}</a>{% else %}{{ row.send }}{% endif %}</td>
    <td>{% if row.filesize %}{{ row.filesize|filesizeformat }}{% endif %}</td>
    <td><ul class="reporterrs">{% if row.lasterror %}<li><a href="{% url 'bots:incoming' %}/?reportidta={{ row.idta }}&statust=1" class="button ico-err" title="{% trans 'View file errors' %}">{{ row.lasterror }} {% trans 'files with errors' %}</a></li>{% endif %}
      {% if row.lastok %}<li><a href="{% url 'bots:incoming' %}/?reportidta={{ row.idta }}&statust=2" class="button ico-err" title="{% trans 'View incoming' %}">{{ row.lastok }} {% trans 'files got stuck' %}</a></li>{% endif %}
      {% if row.lastopen %}<li><a href="{% url 'bots:incoming' %}/?reportidta={{ row.idta }}&statust=0" class="button ico-err" title="{% trans 'View incoming' %}">{{ row.lastopen }} {% trans 'system errors' %}</a></li>{% endif %}
      {% if row.processerrors %}<li><a href="{% url 'bots:process' %}/?reportidta={{ row.idta }}" class="button ico-err" title="{% trans 'View process errors' %}">{{ row.processerrors }} {% trans 'errors in processes' %}</a></li>{% endif %}
      {% if row.status and row.lastreceived and not row.send %}<li><a href="{% url 'bots:outgoing' %}/?reportidta={{ row.idta }}&statust=1&popup=1" target="_blank" class="button ico-err">{% trans 'View out-communication errors' %}</a></li>{% endif %}
    </ul></td>
    {% include 'bots/botstable/td/rsrv1.html' %}
    <td>{% if row.acceptance %}<b class="ico-yes"></b>{% endif %}</td>
</tr>
{% endfor %}</tbody>
{% endblock %}